name: Docker Push

on:
  push:

jobs:
  build-and-push:
    runs-on: ubuntu-20.04

    steps:
      - name: Get Code
        uses: actions/checkout@v2

      - name: Get Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Build Jar file
        run: mvn clean install

      - name: Docker login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/my-app:latest
